version: "3.7"
services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    ports:
      - 80:80
#{cfg.tls}      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./config/.htpasswd:/etc/.htpasswd
      - {cfg.traefik.acme}:/etc/traefik/acme
      - {cfg.traefik.log}:/var/log/traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`{cfg.traefik.domain}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.usersFile=/etc/.htpasswd
#{cfg.tls}      - traefik.http.routers.api.tls=true
#{cfg.tls}      - traefik.http.routers.api.tls.certresolver=letsEncrypt
    networks:
      - web
      - traefik
  whoami:
    image: containous/whoami:v1.5.0
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`{cfg.whoami.domain}`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.middlewares=auth
#{cfg.tls}      - traefik.http.routers.whoami.tls=true
#{cfg.tls}      - traefik.http.routers.whoami.tls.certresolver=letsEncrypt
    networks:
      - traefik
networks:
  web:
    external: true
  traefik:
    external: false