version: "3.7"
services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 80:80
      #{cfg.tls}- 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./config/traefik/provider.yml:/etc/traefik/provider.yml
      - ./config/.htpasswd:/etc/.htpasswd
      - {cfg.traefik.acme}:/etc/traefik/acme
      - {cfg.traefik.log}:/var/log/traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`{cfg.traefik.domain}`)
      - traefik.http.routers.traefik.middlewares=auth@file
      - traefik.http.routers.traefik.service=api@internal
      #{!cfg.tls}- traefik.http.routers.traefik.entrypoints=web
      #{cfg.tls}- traefik.http.routers.traefik.entrypoints=webSecure
      #{cfg.tls}- traefik.http.routers.traefik.tls.certresolver=letsEncrypt
    networks:
      - web
      - traefik
  whoami:
    image: containous/whoami:v1.5.0
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`{cfg.whoami.domain}`)
      - traefik.http.routers.whoami.middlewares=auth@file
      #{!cfg.tls}- traefik.http.routers.whoami.entrypoints=web
      #{cfg.tls}- traefik.http.routers.whoami.entrypoints=webSecure
      #{cfg.tls}- traefik.http.routers.whoami.tls.certresolver=letsEncrypt
    networks:
      - traefik
networks:
  web:
    external: true
  traefik:
    external: false
    name: traefik