# Middlewares
# @see https://docs.traefik.io/v2.2/middlewares/overview/
http:
  middlewares:
    # The BasicAuth middleware is a quick way to restrict access to your services to known users.
    # @see https://docs.traefik.io/v2.2/middlewares/basicauth/
    auth:
      basicAuth:
        # The usersFile option is the path to an external file that contains the authorized users for the middleware.
        # @see https://docs.traefik.io/v2.2/middlewares/basicauth/
        usersFile: /etc/.htpasswd