# Config for v2.2
# Official documentation
# @see https://docs.traefik.io/v2.2/

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Enabling the docker provider
# @see https://docs.traefik.io/v2.2/providers/docker/
providers:
  docker:
    # Expose containers by default through Traefik.
    # If set to false, containers that don't have a traefik.enable=true label
    # will be ignored from the resulting routing configuration.
    # @see https://docs.traefik.io/providers/docker/#exposedbydefault
    exposedByDefault: false

    # Defines a default docker network to use for connections to all containers.
    # This option can be overridden on a container basis with the traefik.docker.network label.
    # @see https://docs.traefik.io/providers/docker/#network
    network: traefik

# HTTPS redirection (80 to 443)
# @see https://docs.traefik.io/v2.2/routing/entrypoints/
entryPoints:
  web:
    address: :80
  #{cfg.tls}webSecure:
    #{cfg.tls}address: :443

# Enable ACME (Let's Encrypt): automatic SSL
# @see https://docs.traefik.io/v2.2/https/acme/
certificatesResolvers:
  letsEncrypt:
    acme:
      # Email address used for registration
      email: '{cfg.email}'

      # File or key used for certificates storage.
      storage: /etc/traefik/acme/acme.json

      # Use https on a simple service exposed with Traefik
      httpChallenge:
        entryPoint: web

# Writing logs to a file
# @see https://docs.traefik.io/v2.2/observability/logs/
log:
  # By default, the logs are written to the standard output.
  # You can configure a file path instead using the filePath option.
  filePath: /var/log/traefik/traefik.log

  # By default, the logs use a text format (common),
  # but you can also ask for the json format in the format option
  format: json

  # By default, the level is set to ERROR
  # Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
  level: DEBUG

# Enable the access logs.
# By default, logs are written to stdout, in text format
# @see https://docs.traefik.io/v2.2/observability/access-logs/
accessLog:
  # By default access logs are written to the standard output.
  # To write the logs into a log file, use the filePath option
  filePath: /var/log/traefik/access.log

  # By default, the logs use a text format (common),
  # but you can also ask for the json format in the format option
  format: json

# If you enable the API, a new special service
# named api@internal is created and can then be referenced in a router
# @see https://docs.traefik.io/v2.2/operations/api/
api:
  # Enable the API in insecure mode, which means that
  # the API will be available directly on the entryPoint named traefik
  insecure: false

  # Enable the dashboard
  dashboard: true